[package]
name = "hub_canister_api"
version.workspace = true
edition.workspace = true

[dependencies]
common_canister_types = { workspace = true }
common_contract_api = { workspace = true }
candid = { workspace = true }
serde = { workspace = true }
